language: node_js
node_js:
- '12'
services:
- mysql
- redis-server
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS alpha;'
script:
- npm run ci
after_script:
- npm i codecov && codecov
jobs:
  include:
  - stage: release
    node_js: 12
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
  - stage: deploy to heroku
    node_js: 12
    deploy:
      after_script: skip
      before_install: skip
      script: skip
      provider: heroku
      api_key:
        secure: ASxdVBQmfptdOXlhdlmFVIVXvzuiukeXgaIBurdtgQ++j+SwxMb0fHtk7xOnoXr6BgQca0fgW60pJsbe645Fl2XybHqvTWciBjxPoZMitl3otLc6ZNdjlYA2fZvRqOTBEMsNw22jUyzHHpuNcKlkQhVQUouMaPGArbeYIc+xAHldMcSoLQ5gb7X4DF08S2JnITNoG3SoEU4NcG03kwtuAQfxdvuEA87yjbkhxFIK4HvSK6Zoju7CA4Oe4CiSZlqk3GWDGjMiYECVPQetYjG9IYlvXyt8EbuhoxCfE2r777HJ9z0VBadpkSTW3TB7I/vcBr20M38pAtbbK91o8xTN4P7eG0+zNDfJgGQl931rKTr7sZ1W9zgN3avG9lGdGs/cRmwbaDlVkcZnW+yzeOKCYb0ruO20h2D9G6Csloe1XCl2VUgyRzv2YJ3UGo7fyzvTfOPZ4Oq4im4Y39nOO4K6dUxxKS+pgf/nFSGID1tIk6fvZf48ZrgLzWyHhMQHdUqq1llfvIwzrCuQ0mWZmUaGX3fiEMd8AAxbU1q3JYMQ042/8lJ9e71oHNnchlicbVTO/3c6fbWggQmQlVg8WU02uyQ1ppEXz8eNVxx7BB6Hn8NkTKYb6g6H4a7QrOrmt8dUzV6gV/2jT9RluRqrqXGyreP3VHWzK9kIAExgNAR+gao=
      app: uniheart
      skip_cleanup: true
