environment:
  MYSQL_PWD: 'Password12!'
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '9'
    - nodejs_version: '10'

install:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - '@ECHO Redis Started'
  - ps: Install-Product node $env:nodejs_version
  - npm i

before_test:
  - ps: >-
    "C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin\\mysql" -e "CREATE DATABASE IF NOT EXISTS alpha;" --user=root

test_script:
  - node --version
  - npm --version
  - "C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin\\mysql" -e "CREATE DATABASE IF NOT EXISTS alpha;" --user=root
  - npm run ci

build: off
services:
  - redis-server
  - mysql
