# for intel/amd64

version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  local-mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    depends_on:
      local-mysql:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: local-mysql
