apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha
    tier: backend
    deployedBy: deploy-node-app
  name: alpha
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alpha
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alpha
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: jefftian/alpha
          imagePullPolicy: Always
          name: alpha
          ports:
            - containerPort: 7001
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: alpha-secrets
#          readinessProbe:
#            httpGet:
#              port: 7001
#              path: /
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
