apiVersion: v1
kind: Service
metadata:
  name: alpha
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 7001
      protocol: TCP
      targetPort: 7001
  selector:
    app: alpha
    tier: backend
